// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/google/wire"
	"go-kratos/conf"
	"go-kratos/internal/repo"
	"go-kratos/internal/service"
	"go-kratos/log"
	"go-kratos/pkg/etcd"
	"go-kratos/pkg/jeager"
	"go-kratos/server"
)

// Injectors from wire.go:

func App() *kratos.App {
	config := conf.LoadConfig()
	loggerLogger := logger.NewLogger(config)
	jeager.TracerProvider(loggerLogger, config)
	db := repo.NewMysql(config, loggerLogger)
	client := repo.NewRedis(config, loggerLogger)
	data := repo.NewData(db, client)
	demo := service.NewDemo(data, loggerLogger)
	grpcServer := server.NewGrpcServer(config, loggerLogger, demo)
	registry := etcd.NewEtcd(loggerLogger, config)
	app := server.NewKratosServer(grpcServer, registry, config)
	return app
}

// wire.go:

var providerSet = wire.NewSet(conf.LoadConfig, logger.NewLogger, jeager.TracerProvider, etcd.NewEtcd, repo.NewMysql, repo.NewRedis, repo.NewData, service.NewDemo, server.NewGrpcServer, server.NewKratosServer)
