// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.10
// source: api/v1/demo.proto

package api

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostHelloRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *PostHelloRequest) Reset() {
	*x = PostHelloRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_demo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostHelloRequest) ProtoMessage() {}

func (x *PostHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_demo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostHelloRequest.ProtoReflect.Descriptor instead.
func (*PostHelloRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_demo_proto_rawDescGZIP(), []int{0}
}

func (x *PostHelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PostHelloResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *PostHelloResponse) Reset() {
	*x = PostHelloResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_demo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostHelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostHelloResponse) ProtoMessage() {}

func (x *PostHelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_demo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostHelloResponse.ProtoReflect.Descriptor instead.
func (*PostHelloResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_demo_proto_rawDescGZIP(), []int{1}
}

func (x *PostHelloResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetHelloRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age  string `protobuf:"bytes,2,opt,name=age,proto3" json:"age,omitempty"`
}

func (x *GetHelloRequest) Reset() {
	*x = GetHelloRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_demo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHelloRequest) ProtoMessage() {}

func (x *GetHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_demo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHelloRequest.ProtoReflect.Descriptor instead.
func (*GetHelloRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_demo_proto_rawDescGZIP(), []int{2}
}

func (x *GetHelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetHelloRequest) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

type GetHelloResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *GetHelloResponse) Reset() {
	*x = GetHelloResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_demo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHelloResponse) ProtoMessage() {}

func (x *GetHelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_demo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHelloResponse.ProtoReflect.Descriptor instead.
func (*GetHelloResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_demo_proto_rawDescGZIP(), []int{3}
}

func (x *GetHelloResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_api_v1_demo_proto protoreflect.FileDescriptor

var file_api_v1_demo_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x76, 0x32, 0x2f,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x26, 0x0a, 0x10, 0x50, 0x6f, 0x73, 0x74, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x25, 0x0a, 0x11, 0x50, 0x6f,
	0x73, 0x74, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x22, 0x37, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x67, 0x65, 0x22, 0x24, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x32, 0xe3, 0x01, 0x0a, 0x0b, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x12, 0x7c, 0x0a, 0x08, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x18, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x6f, 0x73, 0x74, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x3b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14, 0x22, 0x0f, 0x2f, 0x73, 0x61, 0x79, 0x2d,
	0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2d, 0x70, 0x6f, 0x73, 0x74, 0x3a, 0x01, 0x2a, 0x92, 0x41, 0x1e,
	0x62, 0x1c, 0x0a, 0x1a, 0x0a, 0x0a, 0x42, 0x65, 0x61, 0x72, 0x65, 0x72, 0x41, 0x75, 0x74, 0x68,
	0x12, 0x0c, 0x0a, 0x0a, 0x42, 0x65, 0x61, 0x72, 0x65, 0x72, 0x41, 0x75, 0x74, 0x68, 0x12, 0x56,
	0x0a, 0x09, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x32, 0x12, 0x17, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x16,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x10, 0x12, 0x0e, 0x2f, 0x73, 0x61, 0x79, 0x2d, 0x68, 0x65, 0x6c,
	0x6c, 0x6f, 0x2d, 0x67, 0x65, 0x74, 0x42, 0x46, 0x5a, 0x0a, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31,
	0x3b, 0x61, 0x70, 0x69, 0x92, 0x41, 0x37, 0x12, 0x10, 0x0a, 0x09, 0x78, 0x61, 0x77, 0x20, 0x6d,
	0x69, 0x63, 0x72, 0x6f, 0x32, 0x03, 0x31, 0x2e, 0x30, 0x5a, 0x23, 0x0a, 0x21, 0x0a, 0x0a, 0x42,
	0x65, 0x61, 0x72, 0x65, 0x72, 0x41, 0x75, 0x74, 0x68, 0x12, 0x13, 0x08, 0x02, 0x1a, 0x0d, 0x41,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x20, 0x02, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_demo_proto_rawDescOnce sync.Once
	file_api_v1_demo_proto_rawDescData = file_api_v1_demo_proto_rawDesc
)

func file_api_v1_demo_proto_rawDescGZIP() []byte {
	file_api_v1_demo_proto_rawDescOnce.Do(func() {
		file_api_v1_demo_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_demo_proto_rawDescData)
	})
	return file_api_v1_demo_proto_rawDescData
}

var file_api_v1_demo_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_v1_demo_proto_goTypes = []interface{}{
	(*PostHelloRequest)(nil),  // 0: api.v1.PostHelloRequest
	(*PostHelloResponse)(nil), // 1: api.v1.PostHelloResponse
	(*GetHelloRequest)(nil),   // 2: api.v1.GetHelloRequest
	(*GetHelloResponse)(nil),  // 3: api.v1.GetHelloResponse
}
var file_api_v1_demo_proto_depIdxs = []int32{
	0, // 0: api.v1.HelloServer.SayHello:input_type -> api.v1.PostHelloRequest
	2, // 1: api.v1.HelloServer.SayHello2:input_type -> api.v1.GetHelloRequest
	1, // 2: api.v1.HelloServer.SayHello:output_type -> api.v1.PostHelloResponse
	3, // 3: api.v1.HelloServer.SayHello2:output_type -> api.v1.GetHelloResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_demo_proto_init() }
func file_api_v1_demo_proto_init() {
	if File_api_v1_demo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_demo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostHelloRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_demo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostHelloResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_demo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHelloRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_demo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHelloResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_demo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_demo_proto_goTypes,
		DependencyIndexes: file_api_v1_demo_proto_depIdxs,
		MessageInfos:      file_api_v1_demo_proto_msgTypes,
	}.Build()
	File_api_v1_demo_proto = out.File
	file_api_v1_demo_proto_rawDesc = nil
	file_api_v1_demo_proto_goTypes = nil
	file_api_v1_demo_proto_depIdxs = nil
}
