// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/v1/demo2.proto

package api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Hello2Request with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Hello2Request) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Hello2Request with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in Hello2RequestMultiError, or
// nil if none found.
func (m *Hello2Request) ValidateAll() error {
	return m.validate(true)
}

func (m *Hello2Request) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := Hello2RequestValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Age

	if len(errors) > 0 {
		return Hello2RequestMultiError(errors)
	}

	return nil
}

// Hello2RequestMultiError is an error wrapping multiple validation errors
// returned by Hello2Request.ValidateAll() if the designated constraints
// aren't met.
type Hello2RequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Hello2RequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Hello2RequestMultiError) AllErrors() []error { return m }

// Hello2RequestValidationError is the validation error returned by
// Hello2Request.Validate if the designated constraints aren't met.
type Hello2RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Hello2RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Hello2RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Hello2RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Hello2RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Hello2RequestValidationError) ErrorName() string { return "Hello2RequestValidationError" }

// Error satisfies the builtin error interface
func (e Hello2RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHello2Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Hello2RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Hello2RequestValidationError{}

// Validate checks the field values on Hello2Response with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Hello2Response) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Hello2Response with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in Hello2ResponseMultiError,
// or nil if none found.
func (m *Hello2Response) ValidateAll() error {
	return m.validate(true)
}

func (m *Hello2Response) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Msg

	// no validation rules for Message

	if len(errors) > 0 {
		return Hello2ResponseMultiError(errors)
	}

	return nil
}

// Hello2ResponseMultiError is an error wrapping multiple validation errors
// returned by Hello2Response.ValidateAll() if the designated constraints
// aren't met.
type Hello2ResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Hello2ResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Hello2ResponseMultiError) AllErrors() []error { return m }

// Hello2ResponseValidationError is the validation error returned by
// Hello2Response.Validate if the designated constraints aren't met.
type Hello2ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Hello2ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Hello2ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Hello2ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Hello2ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Hello2ResponseValidationError) ErrorName() string { return "Hello2ResponseValidationError" }

// Error satisfies the builtin error interface
func (e Hello2ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHello2Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Hello2ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Hello2ResponseValidationError{}
